version: '3.8'  # 指定 Compose 文件格式版本
services:       # 定义所有要运行的服务容器
  napcat:
    environment:
        - NAPCAT_UID=${NAPCAT_UID}
        - NAPCAT_GID=${NAPCAT_GID}
    ports:
        - 3000:3000
        - 3001:3001
        - 6099:6099
    volumes:
        - /app/.config/QQ:/app/.config/QQ
        - /app/napcat/config:/app/napcat/config
    container_name: napcat
    network_mode: bridge
    restart: always
    image: docker.1ms.run/mlikiowa/napcat-docker